[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Cấu hình nạp qua ST-Link
upload_protocol = stlink

; Tốc độ hiển thị màn hình Serial
monitor_speed = 9600

; Tự động tải thư viện SHT30 và SHT4x (cho chắc)
lib_deps = 
    sensirion/Sensirion I2C SCD4x @ ^0.4.0
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    claws/BH1750 @ ^1.3.0
	adafruit/Adafruit SHT31 Library @ ^2.2.0
	adafruit/Adafruit BusIO
	Wire
    SPI

; Cấu hình để in được chữ ra cổng Serial (USB CDC)
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x5740
	-D USB_MANUFACTURER="Unknown"
	-D USB_PRODUCT="BLUEPILL_F103C8"
	-D HAL_PCD_MODULE_ENABLED