[env:bluepill_f103c8_mock]
platform  = ststm32
board     = bluepill_f103c8
framework = arduino

upload_protocol = stlink
debug_tool      = stlink

monitor_port = socket://localhost:19021

lib_deps =
    vshymanskyy/TinyGSM @ ^0.11.7
    knolleary/PubSubClient @ ^2.8
    arduino-libraries/ArduinoHttpClient @ ^0.6.1

build_flags =
    -Wl,-u_printf_float
    -Wl,-u_scanf_float

build_src_filter = +<*> -<.git/>